apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "elasticsearch.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "elasticsearch.fullname" . }}-selfsigned-ca
spec:
  isCA: true
  commonName: {{ include "elasticsearch.fullname" . }}-selfsigned-ca
  secretName: {{ include "elasticsearch.fullname" . }}-root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    kind: ClusterIssuer
    name: {{ include "elasticsearch.fullname" . }}-selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "elasticsearch.fullname" . }}-ca-issuer
spec:
  ca:
    secretName: {{ include "elasticsearch.fullname" . }}-root-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "elasticsearch.fullname" . }}-cert
spec:
  isCA: false
  dnsNames:
    {{- range .Values.elasticsearch.nodeSets }}
    - {{ include "elasticsearch.fullname" $ }}-{{ .name }}-http
    - {{ include "elasticsearch.fullname" $ }}-{{ .name }}-http.{{ $.Release.Namespace }}.svc
    - {{ include "elasticsearch.fullname" $ }}-{{ .name }}-http.{{ $.Release.Namespace }}.svc.cluster.local
    {{- end }}
  subject:
    organizations:
      - {{ include "elasticsearch.fullname" . }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    kind: Issuer
    name: {{ include "elasticsearch.fullname" . }}-ca-issuer
  secretName: {{ include "elasticsearch.fullname" . }}-cert
